"""initial schema"""
revision = '586e73123349'
down_revision = None
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('authorization_reference', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('approved_targets', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('scan_window', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagements_public_id'), 'engagements', ['public_id'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('scanner_versions', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_engagement_id'), 'scans', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_scans_public_id'), 'scans', ['public_id'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('reachability', sa.String(length=30), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=64), nullable=True),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'ip', name='uq_scan_asset_ip')
    )
    op.create_index(op.f('ix_assets_ip'), 'assets', ['ip'], unique=False)
    op.create_index(op.f('ix_assets_scan_id'), 'assets', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('engagement_public_id', sa.String(length=32), nullable=False),
    sa.Column('asset_ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('service_version', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=False),
    sa.Column('cve', sa.JSON(), nullable=False),
    sa.Column('cwe', sa.JSON(), nullable=False),
    sa.Column('cpe', sa.JSON(), nullable=False),
    sa.Column('cvss_v31_score', sa.Float(), nullable=True),
    sa.Column('cvss_v31_vector', sa.String(length=255), nullable=True),
    sa.Column('cvss_v40_score', sa.Float(), nullable=True),
    sa.Column('cvss_v40_vector', sa.String(length=255), nullable=True),
    sa.Column('cisa_kev', sa.Boolean(), nullable=False),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('scanner_rule_id', sa.String(length=255), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('risk_acceptance_expiry', sa.Date(), nullable=True),
    sa.Column('assigned_owner', sa.String(length=255), nullable=True),
    sa.Column('target_remediation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_asset_ip'), 'findings', ['asset_ip'], unique=False)
    op.create_index(op.f('ix_findings_engagement_public_id'), 'findings', ['engagement_public_id'], unique=False)
    op.create_index(op.f('ix_findings_finding_id'), 'findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_db_id', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('file_location', sa.String(length=500), nullable=True),
    sa.Column('redacted_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_db_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_finding_db_id'), 'evidence', ['finding_db_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('cpe', sa.JSON(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('encryption', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=40), nullable=False),
    sa.Column('source_scanner', sa.String(length=50), nullable=False),
    sa.Column('raw_evidence_location', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_asset_id'), 'services', ['asset_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_asset_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_evidence_finding_db_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_engagement_public_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_ip'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_assets_scan_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_scans_public_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_engagement_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_engagements_public_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

